import logging
import os


API_HOST = os.environ.get("API_HOST", "http://localhost:10000").rstrip('/')

DATA_API_HOST = "https://invest.venturasecurities.com"

SSO_LOGIN_URL = "https://invest2.venturasecurities.com/sso/sign-in"
nifty_trader_auth = 'Basic <>'

connection_headers = {}
master = {}

def _build_api_headers(connection_id: str) -> dict[str, str]:
    if not connection_id:
        raise ValueError(f"connection_id is required {TRY_LOGIN}")

    if not connection_headers:
        raise ValueError(f"No headers found for connection ID: {connection_id} {TRY_LOGIN}")

    try:
        logging.debug("Authenticated and established connection")
        return {
            "Content-Type": "application/json",
            "Authorization": connection_headers[connection_id]["Authorization"],
            "session_id": connection_headers[connection_id]["session_id"],
            "x-client-id": connection_headers[connection_id]["client_id"],
            'niftytraderauth': 'Basic <>',
        }
    except KeyError as e:
        missing = e.args[0]
        raise ValueError(
            f"Missing required header field '{missing}' for connection ID: {connection_id} {TRY_LOGIN}"
        ) from None


DISCLAIMER = '''
Scope Restriction
    1. Only respond to queries that are strictly finance-related (e.g., markets, trading, investing, valuation, risk management, regulations, financial data, etc.).
    2. Politely decline or redirect if the user asks about topics outside finance.

Research Recommendation Handling
    1. If the user requests research recommendations, do not generate your own.
    2. Instead, use the Ventura Securities team's research calls tool.

Disclaimer Requirement
    - Always include a disclaimer in financial responses. The disclaimer must clearly state that:
        1. The information is generated by AI and may be inaccurate or incomplete.
        2. Users should conduct their own due diligence.
        3. No financial decisions should be made solely based on the provided data.
    
    - if any data is not offered by the tools then you can get it from the internet and tell the user as well. Make sure that you don't fetch data from any indian broker other than Ventura. Non broker data sources are fine. 
    The disclaimer should remain short, professional, and unambiguous.
'''

TRY_LOGIN = '''
    if you got "No headers found for connection ID" message from the response, please call the login tool and ask the user to login again.
'''
